name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Modify package-lock.json
        run: |
          cd data-story-portfolio/frontend
          if [ -f "package-lock.json" ]; then
            # Remove fsevents entries from package-lock.json
            jq 'del(.. | .fsevents? | select(.))' package-lock.json > package-lock.json.tmp
            mv package-lock.json.tmp package-lock.json
          fi
          

      - name: Install dependencies
        run: |
          cd data-story-portfolio/frontend
          npm install --legacy-peer-deps --no-optional --force

      - name: Build
        run: |
          cd data-story-portfolio/frontend
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./data-story-portfolio/frontend/dist
