name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Modify package.json to remove fsevents
        run: |
          cd data-story-portfolio/frontend
          if [ -f "package.json" ]; then
            # Remove fsevents from dependencies and devDependencies
            jq 'del(.dependencies.fsevents) | del(.devDependencies.fsevents)' package.json > package.json.tmp
            mv package.json.tmp package.json
          fi

      - name: Install dependencies
        run: |
          cd data-story-portfolio/frontend
          npm install --legacy-peer-deps --no-optional --force

      - name: Build
        run: |
          cd data-story-portfolio/frontend
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./data-story-portfolio/frontend/dist
